version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dev-aws-eks"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-low6gx52exms"
s3_prefix = "dev-aws-eks"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
