AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: dev-aws-eks

Parameters:
  Organization:
    Type: String
    Default: organizationname
  Project:
    Type: String
    Default: projectname
  NodeEnv:
    Type: String
    Default: dev
  Region:
    Type: String
    Default: ap-southeast-1
  
Resources:
  EKSRole:
    Type: AWS::Serverless::Application
    Properties:
      Location: './stacks/eks-role.yml'
  
  EKSResources:
    Type: AWS::Serverless::Application
    Properties:
      Location: './stacks/eks-resources.yml'
      Parameters:
        Organization: !Ref Organization
        Project: !Ref Project
        NodeEnv: !Ref NodeEnv

  EKSCustomVPC:
    Type: AWS::Serverless::Application
    Properties:
      Location: './stacks/eks-vpc.yml'
      Parameters:
        Organization: !Ref Organization
        Project: !Ref Project
        NodeEnv: !Ref NodeEnv
        Region: !Ref Region
  
  EKSCluster:
    Type: AWS::Serverless::Application
    Properties:
      Location: './stacks/eks-cluster.yml' 
      Parameters:
        Organization: !Ref Organization
        Project: !Ref Project
        NodeEnv: !Ref NodeEnv
        NodeInstanceRoleArn: !GetAtt EKSRole.Outputs.NodeInstanceRoleArn
        EksClusterRoleArn: !GetAtt EKSRole.Outputs.EksClusterRoleArn
        ControlPlaneSecurityGroupId: !GetAtt EKSCustomVPC.Outputs.ControlPlaneSecurityGroupId
        PublicSubnet01Id: !GetAtt EKSCustomVPC.Outputs.PublicSubnet01Id
        PublicSubnet02Id: !GetAtt EKSCustomVPC.Outputs.PublicSubnet02Id
        # PrivateSubnet01Id: !GetAtt EKSCustomVPC.Outputs.PrivateSubnet01Id
        # PrivateSubnet02Id: !GetAtt EKSCustomVPC.Outputs.PrivateSubnet02Id

  
