apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image-service
  template:
    metadata:
      labels:
        app: image-service
    spec:
      containers:
        - name: image-service
          image: 396460956865.dkr.ecr.ap-southeast-1.amazonaws.com/dev-k8s-container-repo:maya-image
          ports:
            - containerPort: 8080