# cluster.yaml
# A cluster with one managed nodegroups
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: managed-cluster
  region: ap-southeast-1

vpc:
  nat:
    gateway: Disable

managedNodeGroups:
  - name: managed-ng-1
    instanceType: t2.micro
    amiFamily: Ubuntu2004
    availabilityZones: ["ap-southeast-1a"]
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    volumeSize: 20
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
      # publicKeyPath: ~/.ssh/ec2_id_rsa.pub
      # sourceSecurityGroupIds: ["sg-00241fbb12c607007"] # new feature for restricting SSH access to certain AWS security group IDs
    labels: { role: worker }
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
        autoScaler: true