AWSTemplateFormatVersion: "2010-09-09"
Description: Amazon EKS - Cluster

Parameters:
  NodeEnv:
    Type: String
  Region:
    Type: String
  ProjectName:
    Type: String
  NodeInstanceRoleArn:
    Type: String
  eksClusterRoleArn:
    Type: String
  ControlPlaneSecurityGroupId:
    Type: String
  PublicSubnet01Id:
    Type: String
  PublicSubnet02Id:
    Type: String

Resources:
  # create the cluster
  ClusterEks:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Sub '${NodeEnv}-k8s-kluster'
      ResourcesVpcConfig: 
        SecurityGroupIds: 
          - !Ref ControlPlaneSecurityGroupId
        SubnetIds: 
          - !Ref PublicSubnet01Id
          - !Ref PublicSubnet02Id
      RoleArn: !Ref eksClusterRoleArn
      # Version: 1.21.2
  
  WebServerNodeGroup:
    DependsOn:
      - ClusterEks
    Type: AWS::EKS::Nodegroup
    Properties: 
      # AmiType: String
      # CapacityType: String
      ClusterName: !Ref ClusterEks
      # DiskSize: Double
      # ForceUpdateEnabled: Boolean
      InstanceTypes: 
        - t2.micro
      # Labels: Json
      # LaunchTemplate: 
        # LaunchTemplateSpecification
      NodegroupName: !Sub '${NodeEnv}-webserver-nodegroup'
      NodeRole: !Ref NodeInstanceRoleArn
      # ReleaseVersion: String
      # RemoteAccess: 
        # RemoteAccess
      ScalingConfig: 
        DesiredSize: 0
        MaxSize: 1
        MinSize: 0
      Subnets: 
        - !Ref PublicSubnet01Id
        - !Ref PublicSubnet02Id
      # Tags: Json
      # Taints: 
      #   - Taint
      # UpdateConfig: 
      #   UpdateConfig
      # Version: String