AWSTemplateFormatVersion: "2010-09-09"
Description: Amazon EKS - Resources

Parameters:
  NodeEnv:
    Type: String
  Region:
    Type: String

Resources:
  ImageStorageS3:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private

  EksContainerRepo:
    Type: AWS::ECR::Repository
    Properties: 
      # EncryptionConfiguration: 
      #   EncryptionConfiguration
      # ImageScanningConfiguration: 
      #   ImageScanningConfiguration
      ImageTagMutability: MUTABLE
      # LifecyclePolicy: 
      #   LifecyclePolicy
      RepositoryName: !Sub '${NodeEnv}-k8s-container-repo'
      # RepositoryPolicyText: Json
      # Tags: 
      #   - Tag

Outputs:
  EksContainerRepoUri:
    Value: !GetAtt EksContainerRepo.RepositoryUri
